# Syvora site core data. No em dashes anywhere.
from services_a import SERVICES_A
from services_b import SERVICES_B

SITE = dict(
    name="Syvora",
    domain="https://syvora.com",
    tagline="The Engine Behind Real Adoption",
    calendly="https://calendly.com/majid-khan-syvora/30min",
    linkedin="https://www.linkedin.com/company/syvora",
    x="https://x.com/thesyvora",
)

SERVICES = {**SERVICES_A, **SERVICES_B}

PRACTICES = {
"blockchain-web3": dict(
    code="SYV-01", name="Blockchain & Web3", n=22, order=1,
    tag="DEEPEST BENCH IN THE STUDIO",
    short="Protocol, contracts, DeFi, tokenization, wallets, and security across the full on-chain stack.",
    meta="Blockchain development practice: 22 engineers covering smart contracts, protocol design, DeFi, tokenization, wallets, and security.",
    lede="Protocol and application engineering across the full on-chain stack. This is where Syvora started, and it remains the standard our other practices are built to match: security-first, adversarial-by-default, and measured in adoption rather than deployments.",
    stats=[("22","ENGINEERS"),("90K+","PRACTICE HOURS DELIVERED"),("20+","MAINNET DEPLOYMENTS"),("15+","CHAINS SHIPPED ON")],
    comp=[("Protocol & Contracts",12),("Infra & Indexing",4),("Security",3),("Web3 Frontend",3)],
    tech=["ethereum","solana","base","arbitrum","polygon","solidity","rust"],
),
"full-stack-engineering": dict(
    code="SYV-02", name="Full Stack Engineering", n=24, order=2,
    tag="LARGEST PRACTICE BY HEADCOUNT",
    short="Web applications, APIs, cloud infrastructure, commerce, and the product layer around every system we ship.",
    meta="Full stack engineering practice: 24 engineers building web applications, APIs, cloud infrastructure, and commerce systems.",
    lede="The product layer around every system we ship: web applications, APIs, dashboards, and commerce. TypeScript-first architecture on cloud-native infrastructure, paired with any other practice or standalone on pure Web2 products.",
    stats=[("24","ENGINEERS"),("85K+","PRACTICE HOURS DELIVERED"),("30+","PRODUCTION APPLICATIONS"),("15+","APPS UNDER MANAGEMENT")],
    comp=[("Frontend",9),("Backend",8),("Platform & DevOps",3),("UI Engineering",4)],
    tech=["typescript","react","nextjs","nodejs","go","postgresql","aws","cloudflare","shopify"],
),
"servicenow": dict(
    code="SYV-03", name="ServiceNow", n=8, order=3,
    tag="ENTERPRISE WORKFLOW ENGINEERING",
    short="ITSM, ITOM, HRSD, custom applications, integrations, and SLA-backed managed services on the Now Platform.",
    meta="ServiceNow practice: certified consultants delivering ITSM, ITOM, HRSD, custom apps, integrations, and managed services.",
    lede="Enterprise workflow engineering on the Now Platform, from greenfield ITSM rollouts to custom scoped applications and the integration architecture that connects ServiceNow to the rest of the enterprise stack. Every engagement is run by certified consultants and measured after go-live.",
    stats=[("8","CERTIFIED CONSULTANTS"),("40+ YRS","COMBINED PLATFORM EXPERIENCE"),("25+","IMPLEMENTATIONS ACROSS THE TEAM"),("CSA·CAD·CIS","CERTIFICATIONS HELD")],
    comp=[("Implementation",4),("Platform Dev",2),("Integrations",1),("Architect",1)],
    tech=["servicenow-itsm","servicenow-itom","servicenow-hrsd","servicenow-app-engine","servicenow-integrationhub","servicenow-now-assist"],
),
"extended-capabilities": dict(
    code="SYV-04", name="Extended Capabilities", n=10, order=4,
    tag="SPECIALIST CAPACITY, ON DEMAND",
    short="AI automation, mobile, data, platform engineering, QA, and growth that plug into any engagement.",
    meta="Extended capabilities practice: AI automation, mobile development, data engineering, DevOps, QA, and technical SEO specialists.",
    lede="Specialist capacity that plugs into any engagement: AI systems, mobile, data, platform, and quality engineering. These teams ship standalone when scope calls for it, and embed inside a product pod when a build needs more surface area.",
    stats=[("10","SPECIALISTS"),("25K+","PRACTICE HOURS DELIVERED"),("15+","AUTOMATION SYSTEMS IN PRODUCTION"),("100%","OF PODS SUPPORTED")],
    comp=[("AI & Automation",4),("Mobile",2),("Data",2),("QA",2)],
    tech=["python","n8n","react-native","flutter","kubernetes","gcp"],
),
}

# category, blurb, points (what we build with it), faq
TECHNOLOGIES = {
"ethereum": dict(name="Ethereum", cat="Chains",
    blurb="The settlement layer where most on-chain value lives. Syvora has deployed protocols, token systems, and DeFi infrastructure on Ethereum mainnet since the practice began.",
    points=["Protocol and DeFi systems with audit-ready Solidity","Token and governance contracts with timelock operations","Gas-optimized architectures reviewed against mainnet costs"],
    services=["smart-contract-development","defi-development","protocol-token-design"]),
"solana": dict(name="Solana", cat="Chains",
    blurb="High-throughput execution for products where latency is the feature. We build Solana programs in Rust with the account-model discipline the runtime demands.",
    points=["On-chain programs in Rust with Anchor where it helps","High-frequency DeFi and consumer app backends","Indexing pipelines tuned for Solana's data volume"],
    services=["smart-contract-development","blockchain-indexing-data","defi-development"]),
"base": dict(name="Base", cat="Chains",
    blurb="Coinbase's L2 has become the default home for consumer crypto. We ship account-abstracted, gas-sponsored experiences that make Base apps feel like normal software.",
    points=["Consumer apps with embedded wallets and sponsored gas","L2 deployments coordinated with mainnet contracts","Onchain commerce and social integrations"],
    services=["wallet-account-abstraction","smart-contract-development","tokenization-rwa"]),
"arbitrum": dict(name="Arbitrum", cat="Chains",
    blurb="The largest DeFi L2 by depth. Syvora deploys and operates protocols on Arbitrum with the oracle and liquidity assumptions that serious TVL requires.",
    points=["DeFi protocol deployments with risk parameters tuned per chain","Cross-chain positions coordinated with mainnet","Sequencer-aware architecture and failure handling"],
    services=["defi-development","cross-chain-interoperability","smart-contract-development"]),
"polygon": dict(name="Polygon", cat="Chains",
    blurb="A pragmatic home for tokenization pilots and high-volume consumer flows. We use Polygon where transaction economics decide the product.",
    points=["RWA and loyalty token rails with enforced transfer rules","High-volume minting and distribution systems","Enterprise pilots that graduate to multichain"],
    services=["tokenization-rwa","smart-contract-development","cross-chain-interoperability"]),
"solidity": dict(name="Solidity", cat="Languages",
    blurb="The language of EVM value. Our Solidity is specified before written, fuzzed before shipped, and documented for the auditors who read it next.",
    points=["Contract systems with Foundry test and invariant suites","Upgradeable architectures chosen deliberately","Gas profiling as part of code review"],
    services=["smart-contract-development","smart-contract-audit-readiness","defi-development"]),
"rust": dict(name="Rust", cat="Languages",
    blurb="Rust powers our Solana programs and the indexers that need to chew through chains at line speed. Memory safety is not optional at these stakes.",
    points=["Solana programs with rigorous account validation","High-throughput chain indexers and data services","Performance-critical backend services"],
    services=["smart-contract-development","blockchain-indexing-data","api-backend-development"]),
"typescript": dict(name="TypeScript", cat="Languages",
    blurb="Our default for product engineering. One typed language across frontend, backend, and tooling keeps pods fast and refactors safe.",
    points=["Full-stack product codebases with end-to-end types","API contracts shared between client and server","Tooling and automation with the same standards as product code"],
    services=["web-application-development","api-backend-development","shopify-commerce-engineering"]),
"python": dict(name="Python", cat="Languages",
    blurb="The workhorse for data and AI systems. We use Python where its ecosystem is the advantage: pipelines, model integration, and analysis.",
    points=["RAG and agent systems with evaluation harnesses","Data pipelines and dbt-adjacent tooling","Automation services with production-grade error handling"],
    services=["ai-agentic-automation","data-engineering-analytics","api-backend-development"]),
"go": dict(name="Go", cat="Languages",
    blurb="Chosen when throughput and operational simplicity matter most. Our Go services are small, observable, and comfortably boring at load.",
    points=["High-throughput APIs and streaming services","Infrastructure tooling and platform services","Latency-sensitive backends with clean concurrency"],
    services=["api-backend-development","performance-reliability-engineering","devops-platform-engineering"]),
"react": dict(name="React", cat="Frontend",
    blurb="The interface layer for nearly everything we ship on the web. Component systems, accessibility, and motion built to production standards.",
    points=["Design systems and component libraries teams ship from","Complex product UIs with measured interaction latency","Dashboards and internal tools that feel like products"],
    services=["web-application-development","product-design-ui-engineering","wallet-account-abstraction"]),
"nextjs": dict(name="Next.js", cat="Frontend",
    blurb="Our default web framework: server components, edge rendering, and the SEO surface programmatic architectures need.",
    points=["Marketing and product sites with programmatic SEO baked in","App Router products with server-first data flow","Edge-rendered experiences on Cloudflare and Vercel"],
    services=["web-application-development","technical-seo-growth","product-design-ui-engineering"]),
"nodejs": dict(name="Node.js", cat="Backend",
    blurb="Product backend velocity in the same language as the frontend. We run Node where iteration speed compounds.",
    points=["REST and GraphQL APIs with typed contracts","Event-driven workers and queue consumers","Realtime services with websocket delivery"],
    services=["api-backend-development","web-application-development","blockchain-indexing-data"]),
"postgresql": dict(name="PostgreSQL", cat="Backend",
    blurb="Our default database, and usually the last one a product needs. Schemas designed for the queries you will actually run.",
    points=["Transactional schemas with zero-downtime migration patterns","Query optimization and index strategy from real plans","Analytics-ready models feeding warehouses cleanly"],
    services=["database-architecture","api-backend-development","data-engineering-analytics"]),
"aws": dict(name="AWS", cat="Cloud",
    blurb="The default hyperscaler for enterprise workloads. We run AWS with Terraform discipline and bills that match forecasts.",
    points=["Terraform-managed environments with review-gated change","Container and serverless architectures sized to workload","Cost engineering that keeps spend flat as usage grows"],
    services=["cloud-infrastructure","devops-platform-engineering","legacy-modernization"]),
"gcp": dict(name="Google Cloud", cat="Cloud",
    blurb="Our pick when the data stack leads: BigQuery-centered platforms with clean IAM and pipelines that stay fresh.",
    points=["BigQuery warehouses modeled with dbt","Cloud Run services with GitOps deployment","Data pipelines with freshness and quality monitors"],
    services=["data-engineering-analytics","cloud-infrastructure","api-backend-development"]),
"cloudflare": dict(name="Cloudflare", cat="Cloud",
    blurb="The edge platform we reach for first on latency-sensitive and cost-sensitive products: Workers, Pages, D1, and R2 doing serious work.",
    points=["Edge APIs and full products on Workers and D1","Global static and hybrid sites on Pages","Zero-egress storage architectures on R2"],
    services=["cloud-infrastructure","web-application-development","shopify-commerce-engineering"]),
"kubernetes": dict(name="Kubernetes", cat="Cloud",
    blurb="Deployed when it earns its complexity. GitOps-managed clusters with golden paths, not YAML sprawl.",
    points=["Cluster architecture with Argo CD and workload standards","Multi-environment platforms with progressive delivery","Migration from hand-built clusters to managed sanity"],
    services=["devops-platform-engineering","cloud-infrastructure","performance-reliability-engineering"]),
"shopify": dict(name="Shopify", cat="Platforms",
    blurb="Commerce infrastructure we ship on weekly: public apps, checkout extensions, and storefronts built to platform rules.",
    points=["Public and custom apps on Remix with Polaris","Checkout UI extensions and sub-30KB theme embeds","Headless storefronts when the business case is real"],
    services=["shopify-commerce-engineering","web-application-development","technical-seo-growth"]),
"react-native": dict(name="React Native", cat="Mobile",
    blurb="Cross-platform mobile that shares brains with your web codebase. Native modules where the platform demands them.",
    points=["iOS and Android apps from one TypeScript codebase","Offline-first data with conflict-aware sync","OTA update pipelines with staged rollout"],
    services=["mobile-app-development","web-application-development","product-design-ui-engineering"]),
"flutter": dict(name="Flutter", cat="Mobile",
    blurb="Our choice for design-heavy mobile products where custom UI is the point. One rendering engine, pixel control everywhere.",
    points=["Custom-branded consumer apps at 60fps","Animation-rich interfaces without per-platform drift","Shared logic across mobile and desktop targets"],
    services=["mobile-app-development","product-design-ui-engineering"]),
"n8n": dict(name="n8n", cat="Platforms",
    blurb="Our orchestration layer for integration-heavy automation: visible workflows, full run logs, and self-hosted control.",
    points=["Agentic AI workflows with human-in-the-loop gates","Cross-system automations with retries and queues","Operations pipelines your team can read and modify"],
    services=["ai-agentic-automation","data-engineering-analytics","api-backend-development"]),
"servicenow-itsm": dict(name="ServiceNow ITSM", cat="ServiceNow",
    blurb="The core of IT service delivery. We implement ITSM with process design first and adoption measured after go-live.",
    points=["Incident, Problem, Change, Request, and Knowledge rollouts","Service catalogs with automated fulfillment","SLA frameworks that reflect operational reality"],
    services=["servicenow-itsm-implementation","servicenow-managed-services","servicenow-service-portal"]),
"servicenow-itom": dict(name="ServiceNow ITOM", cat="ServiceNow",
    blurb="Discovery, Service Mapping, and Event Management that keep the CMDB true without manual heroics.",
    points=["MID Server discovery architecture and tuning","Top-down service maps for impact analysis","Event correlation that cuts alert noise"],
    services=["servicenow-itom-cmdb","servicenow-integrations","servicenow-managed-services"]),
"servicenow-hrsd": dict(name="ServiceNow HRSD", cat="ServiceNow",
    blurb="HR service delivery with the confidentiality model designed in and the employee experience treated as a product.",
    points=["COE-based case management with tiered fulfillment","Lifecycle event orchestration across departments","Employee Center experiences that deflect"],
    services=["servicenow-hrsd-csm","servicenow-service-portal","servicenow-virtual-agent-ai"]),
"servicenow-app-engine": dict(name="ServiceNow App Engine", cat="ServiceNow",
    blurb="Custom applications on the platform, built with product discipline: scoped, tested with ATF, and upgrade-safe.",
    points=["Scoped apps replacing spreadsheet-run processes","Flow Designer automation with error handling","UI Builder workspaces matched to each role"],
    services=["servicenow-custom-app-development","servicenow-service-portal","servicenow-integrations"]),
"servicenow-integrationhub": dict(name="ServiceNow IntegrationHub", cat="ServiceNow",
    blurb="The integration fabric connecting ServiceNow to identity, ERP, CRM, and monitoring, with reconciliation to prove agreement.",
    points=["Spoke-based integrations with credential hygiene","Custom REST interfaces where spokes end","Reconciliation jobs that catch silent drift"],
    services=["servicenow-integrations","servicenow-itom-cmdb","servicenow-custom-app-development"]),
"servicenow-now-assist": dict(name="ServiceNow Now Assist", cat="ServiceNow",
    blurb="Platform generative AI pointed at measurable work: summarization, resolution notes, and deflection with published baselines.",
    points=["Now Assist enablement with guardrails","Virtual Agent conversations on top intents","Accuracy and deflection dashboards leadership can read"],
    services=["servicenow-virtual-agent-ai","servicenow-itsm-implementation","ai-agentic-automation"]),
}

ENGAGEMENT = [
    dict(slug="dedicated-pods", name="Dedicated Product Pods",
        short="A cross-functional team of engineers, a designer, and a lead who own a roadmap end to end.",
        detail="The default for products with momentum. A pod is a stable unit: two to six engineers, a designer when the surface needs one, and a senior lead accountable for outcomes. Weekly demos, transparent burn, and a roadmap owned together.",
        fits="Products with a living roadmap, funded startups, teams replacing agency churn with a stable unit."),
    dict(slug="staff-augmentation", name="Staff Augmentation",
        short="Vetted senior engineers embedded in your team, matched to your stack in days, not months.",
        detail="Your process, your repos, our engineers. Every placement is senior, interviewed by us against real work, and productive inside the first sprint. Swap or scale with two weeks notice.",
        fits="Teams with strong process needing capacity, parental-leave coverage, spikes ahead of launches."),
    dict(slug="fixed-scope", name="Fixed-Scope Delivery",
        short="A defined build with a defined price and date. Scoped, specced, and shipped.",
        detail="For work that can be specified, we will put the spec, the price, and the date in writing and hit all three. Change control is explicit, so surprises are choices rather than discoveries.",
        fits="MVPs, migrations, integrations, audit-readiness passes, and anything a procurement team needs bounded."),
    dict(slug="managed-services", name="Managed Services",
        short="SLA-backed operations, support, and continuous improvement after go-live.",
        detail="Software is not done at launch. Managed services keep systems healthy and improving: flat monthly retainer, defined SLAs, a delivered-enhancements report every month, and upgrades executed on schedule.",
        fits="Live products, ServiceNow instances, protocols needing parameter and upgrade operations."),
]

PROCESS = [
    ("01","Analyze","Pressure-test the idea, map value flow, pick the stack, define V1 scope.",
     "Every engagement starts by making the problem legible: value flow mapping, technical due diligence, and a V1 scope that earns adoption before expansion. You leave this phase with a written spec, a price, and a date."),
    ("02","Build","Design systems, write and test the code, review everything before it ships.",
     "Senior-led pods build in weekly increments with working software demoed every Friday. Code review, automated tests, and documented decisions are the default, not the upgrade."),
    ("03","Launch","Deploy to production, wire integrations, analytics, and your existing tools.",
     "Launch is an engineering phase, not an event: progressive rollout, monitoring in place before traffic, integrations verified with reconciliation, and rollback rehearsed."),
    ("04","Optimize","Track real usage, tune performance, run growth loops, ship updates.",
     "We instrument what we ship and stay accountable to adoption: usage dashboards, performance budgets, and a monthly cadence of improvements driven by real data."),
]

DELTA = [
    ("Discretion","NDA-first, always. Your roadmap stays yours."),
    ("Excellence","Senior-led work, reviewed before it ships."),
    ("Loyalty","We build like owners, for the long relationship."),
    ("Transparency","Weekly demos and honest reporting on scope and burn."),
    ("Accountability","Instrumented outcomes, measured after go-live."),
]

STATS = [("64","ENGINEERS ON BENCH"),("35+","PRODUCTS SHIPPED"),("6+","YRS AVG EXPERIENCE"),("200K+","ENGINEERING HOURS"),("24/5","DELIVERY COVERAGE")]

PAINS = [
    ("HIRING TAKES MONTHS. ROADMAPS DO NOT WAIT.","Pods staffed in days.",
     "Named engineers and live environments inside two weeks, working software on screen by week three."),
    ("FIVE VENDORS. ZERO ACCOUNTABILITY.","One studio across the whole build.",
     "Strategy, design, and engineering in a single team, so nothing falls between contracts."),
    ("AGENCIES SHIP CODE, THEN DISAPPEAR.","Accountable after go-live.",
     "The AIgile process tracks adoption and real usage, with SLA-backed managed services when you want them."),
    ("SENIORS PITCH. JUNIORS BUILD.","The bench you meet is the bench you get.",
     "Senior-led pods, weekly demos, and transparent reporting on scope and burn."),
]
